config/routes.rb
NiteLife::Application.routes.draw do
  devise_for :users

  root 'landing#homepage'

  resources :events 

  resources :user_events

  resources :selected_events

  resources :selected_artists

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :events
  has_many :selected_artists, dependent: :destroy


  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"] )
    else
      all.latest
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  belongs_to :artist

  has_many :selected_events, dependent: :destroy

  before_validation :smart_add_url_protocol
  validates :name, presence: true
  validates :genre, presence: true
  validates :artist, presence: true
  validates :date, presence: true 
  validates :time, presence: true
  validates :venue, presence: true
  validate :must_be_valid_date 
  validates :lastfm_id, uniqueness: true, allow_nil: true
  validates :url, :format => URI::regexp(%w(http https)) 


  validate :date_cannot_be_in_past
  
  has_attached_file :photo, :styles => { 
    :medium => "300x300>", :thumb => "100x100>", :large => "700x700>", :strip => "300X150>"
    }, :default_url => "/images/:style/missing.png"
  
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  
  scope :latest, -> { order(date: :asc, time: :asc)}

  def self.search(search)
    if search
      joins(:artist).where(['events.name ILIKE ? OR events.genre ILIKE ? OR events.venue ILIKE ? OR artists.name ILIKE ?', "%#{search}%" , "%#{search}%" , "%#{search}%", "%#{search}%"] )
    else
      all.latest
    end
  end

  def smart_add_url_protocol
    unless self.url =~ /\Ahttp:\/\// || self.url =~ /\Ahttps:\/\//
      self.url = "http://#{self.url}"
    end
  end

private

  def date_cannot_be_in_past
    if date && date < Date.today
      errors.add(:date, "can't be in the past")
    end    
  end

  def must_be_valid_date
    if !date.is_a?(Date)
      errors.add(:started_at, 'must be a valid date') 
    end
  end
  
end

app/models/selected_artist.rb
class SelectedArtist < ActiveRecord::Base
  belongs_to :user
  belongs_to :artist
  has_many :events, through: :artists
  validates :artist_id, :uniqueness => { :scope => :user_id }
end

app/models/selected_event.rb
class SelectedEvent < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  validates :event_id, :uniqueness => { :scope => :user_id }

  def self.send_reminder_emails
    todays_reminders = check_events
    todays_reminders.each do |selected_event|
      selected_event.deliver_reminder
    end
  end

  def self.check_events
    SelectedEvent.includes(:event, :user).select { |se| se.ready_for_reminder? }
  end
 
  def deliver_reminder
    SelectedEventMailer.event_alert(self).deliver
  end

  def ready_for_reminder?
    self.event.date == Date.today+1.day
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events

  has_many :selected_events
  has_many :selected_artists
  has_many :interested_events, through: :selected_events, class_name: "Event", source: :event
  has_many :artists, through: :selected_artists


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def artist_events
    self.artists.includes(:events).collect(&:events)

    Event.includes(artist: :selected_artists).where(selected_artists: {user_id: self.id} )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def after_sign_in_path_for(resource)
    events_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :authenticate_user!, except:[:index, :show, :homepage]
  
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.artist = Artist.find_or_create_by(name: params[:event][:artist])
    @event.user_id = current_user.id
      if @event.valid?
        @event.save
        NewEventsMailer.confirmation_email(current_user).deliver
        redirect_to @event, notice: 'Event was successfully created.'
      else
        render :new
      end
  end

  def show
    @event = Event.find(params[:id])
    @artist = @event.artist
  end

  def index
    @events = Event.search(params[:search])
  end

  def edit
    @event = Event.find(params[:id])
    @artist = @event.artist
    if current_user.admin || current_user.id == @event.user_id
      @event = Event.find(params[:id])
    else
      redirect_to event_path(@event), notice: "I'm sorry, you don't have permission to edit that event"
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if current_user.admin || current_user.id == @event.user_id
      @event.destroy
      redirect_to events_path, notice: "That event has been deleted"
    else
      redirect_to event_path(@event), notice: "I'm sorry, you don't have permission to delete that event"
    end

  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :genre, :venue, :date, :time, :url, :email, :description, :photo)
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
	layout "landing/landing"
end

app/controllers/selected_artists_controller.rb
class SelectedArtistsController < ApplicationController

  def index
    if user_signed_in?
      @events = Event.search(params[:search])
    else
      redirect_to events_path, notice: 'stop trying to break my site, naughty developer!'
    end
  end

  def create
    @selected_artist = SelectedArtist.new
    @selected_artist.user_id = current_user.id
    @selected_artist.artist_id = Artist.find(params[:artist_id]).id
    @selected_artist.save

    if @selected_artist.save
      redirect_to selected_artists_path
    else
      redirect_to selected_artists_path, notice: "You've already selected that!"
    end
  end

  def destroy
    @selected_artist = SelectedArtist.find(params[:id])
    @selected_artist.destroy
    redirect_to selected_artist_path
  end

end

app/controllers/selected_events_controller.rb
class SelectedEventsController < ApplicationController

  def index
    if user_signed_in?
      @selected_events = SelectedEvent.all
    else
      redirect_to events_path, notice: 'stop trying to break my site, naughty developer!'
    end
  end

  def create
    @selected_event = SelectedEvent.new
    @selected_event.user_id = current_user.id
    @selected_event.event_id = Event.find(params[:event_id]).id
    @selected_event.save

    if @selected_event.save
      redirect_to selected_events_path
    else
      redirect_to selected_events_path, notice: "You've already selected that!"
    end
  end

  def destroy
    @selected_event = SelectedEvent.find(params[:id])
    @selected_event.destroy
    redirect_to selected_events_path
  end

end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController
  
  def index
    if current_user == nil
      redirect_to events_path, notice: 'you need to log in/sign up!'
    elsif current_user.events == nil 
      redirect_to new_events_path, notice: 'you need to create some events!'
    else
      @users_events = current_user.events
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/selected_events_helper.rb
module SelectedEventsHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_event.html.erb
<div class="event-box">
  <div class="event-photo">
    <% if event.photo_url %>
      <img src="<%= event.photo_url %>" >
    <% else %>
      <%= image_tag event.photo.url(:strip) %>
    <% end %>
  </div>
  <div class="event-name">
    <h2 id='fe_text'><%= link_to event.name, event_path(event) %></h2>
    <div id='event-info'>
      <h3><%= event.artist.name %></h3>
      <p><%= event.venue %></p>
      <p><%= event.date.strftime("%m/%d/%Y") %></p>
    </div>
  </div>  
</div>

app/views/events/edit.html.erb
<h2>Editing an event</h2>

<%= form_for @event, html: {class: "nifty_form"}, method: 'put' do |f| %>

  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited
        this film from being saved:</h2>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :artist %>
  <%= f.text_field :artist, value: @event.artist.name %>
  
  <%= f.label :genre %>
  <%= f.text_field :genre %>

  <%= f.label :venue %>
  <%= f.text_field :venue %>

  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.label :time %>
  <%= f.time_field :time %>

  <%= f.label :description %>
  <%= f.text_area :description, size: "100x10" %>

  <%= f.label :photo %>
  <%= f.file_field :photo %>

  <%= f.submit "Update" %>

<% end %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div id='events-reposition'>
  <h2>All Events</h2>
  <% if user_signed_in? %>
    <h3><%= link_to 'Add an event', new_event_path %></h3>
  <% end %>
  <% @events.each do |event| %>
    <% if event.date >= Date.today %>
      	<%= render event %>
    <% end %>
  <% end %>
</div>

app/views/events/new.html.erb
<%= form_for @event, html: {class: "nifty_form", :multipart => true } do |f| %>
  
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited
        this film from being saved:</h2>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "Event Name" %>

  <%= f.label :artist %>
  <% if @event.errors.any? %>
    <%= f.text_field :artist, placeholder: "Artist Playing", value: @event.artist.name %>
  <% else %>
    <%= f.text_field :artist, placeholder: "Artist Playing" %>
  <% end %>
  
  <%= f.label :genre %>
  <%= f.text_field :genre, placeholder: "Genres" %>

  <%= f.label :venue %>
  <%= f.text_field :venue, placeholder: "What Venue?" %>

  <%= f.label :url %>
  <%= f.text_field :url, placeholder: "Web Address" %>

  <%= f.label :email %>
  <%= f.text_field :email, placeholder: "Contact Email" %>

  <%= f.label :date %>
  <%= f.date_field :date%>

  <%= f.label :time %>
  <%= f.time_field :time%>

  <%= f.label :description %>
  <%= f.text_area :description, placeholder: "Add a description of the event", size: "100x10"%>  

  <%= f.label :photo %>
  <%= f.file_field :photo %>


  <%= f.submit "create" %>

<% end %>

app/views/events/show.html.erb
<div class="show-box">
  
  <div class="event-photo-large">
    <div>
      <%if @event.genre == 'Concert' %>
        <%= image_tag "floyd.jpg" %>
      <% else %>
        <%= image_tag @event.photo.url(:large) %>
      <% end %>
    </div>
    <%= @event.name %>
    <h3>Artists: <%= @artist.name %></h3>
      <% if user_signed_in? %>
        <% if current_user.artists.include?(@artist) %>
          <p> You are currently following this artist</p>
        <% else %>
          <%= button_to 'Follow Artist', selected_artists_path(artist_id: @event.artist_id) %>
        <% end %>
      <% end %>
    <div class="event-description">
      
      <p>
        Description: <%= @event.description %>
      </p>
    </div><span id='fe_text'>
    <p>Venue: <%= @event.venue %></p>
    <p>Date: <%= @event.date.strftime("%m/%d/%Y") %></p>
    <p>Time: <%= @event.time.strftime("%I:%M%p") %></p>
    <% unless @event.genre == "Concert" %>
      <p>Genre: <%= @event.genre %></p>
    <% end %>
    <p>Info: <a href='<%= @event.url %>'><%= @event.url %></a>,  <%= @event.email %></p></span> 
  </div>

  <div class='demo-area'>
    <button class='my_clip_button' data-clipboard-target='fe_text' data-clipboard-text='Default clipboard text from attribute' id='d_clip_button' title='Click me to copy to clipboard.'>
      <b>Copy</b>
    </button> details to your clipboard
    <div>
      
      <% if user_signed_in? %> 
        <% if current_user.interested_events.include?(@event) %>
          <p>You've already selected this event.</p>
        <% else %>
      <ul>
        <li><h4>Like the look of this event? Add it to your feed</h4>
          <%= button_to('Include', selected_events_path(event_id: @event.id), class: 'btn btn-large btn-primary') %></li>
      <% end %>

          <% if current_user.id == @event.user_id %>  
            <li><%= link_to('Edit', edit_event_path(@event), class: 'btn btn-large btn-primary')  %></li>
            <li><%= button_to('Delete', event_path(@event), class: 'btn btn-large btn-primary', method: :delete, data: {confirm: 'Are you sure?' })%></li>
        </ul>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <%= link_to 'Back', events_path %>


  <script>
    $(document).ready(function() {
      var clip = new ZeroClipboard($("#d_clip_button"))
    });
    $("#clear-test").on("click", function(){
      $("#fe_text").val("Copy me!");
      $("#testarea").val("");
    });
  </script>  

app/views/landing/homepage.html.erb
<div class="slide story" id="slide-1" data-slide="1">
    <div class="container">
      <div id="home-row-1" class="row clearfix">
        <div class="col-12">
          <h1 class="font-semibold">
            <strong>Welcome</strong> to your <span class="font-thin">NiteLife</span></h1>
          <br>
          <br>
        </div><!-- /col-12 -->
      </div><!-- /row -->
    </div><!-- /container -->
  </div><!-- /slide1 -->

  <!-- === Slide 5 === -->
  <div class="slide story" id="slide-5" data-slide="5">
    <div class="container">
      <div class="row title-row">
        <h2 class="font-thin">Never miss <span class="font-semibold">a great night out again</span></h2>
        </div>
        <div class="row content-row">
      <div class="col-sm-1 hidden-sm">&nbsp;</div>
        <ul>
          <li>
            <div class="col-12 col-sm-2">
              <p><i class="icon icon-bolt"><%= image_tag "treble_clef.png" %> </i></p>
              <h2 class="font-thin">Register<br><span class="font-semibold" >Your Events</span></h2>
              <h4 class="font-thin">Add your own events so people know about your performances.</h4>
            </div>
          </li>
          <li>
            <div class="col-12 col-sm-2">
              <p><i class="icon icon-cog"><%= image_tag "quaver.png" %></i></p>
              <h2 class="font-thin">Follow<br><span class="font-semibold">Great Artists</span></h2>
              <h4 class="font-thin">Follow your favourite artists so you never miss a show.</h4>
            </div>
          </li>
          <li>
            <div class="col-12 col-sm-2">
              <p><i class="icon icon-cloud"><%= image_tag "bass.png" %></i></p>
              <h2 class="font-thin">Don't<br><span class="font-semibold">Miss Out</span></h2>
              <h4 class="font-thin">Search a huge listing of music events and save your favourites to your feed.</h4>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <%= button_to('Enter', events_path, class: 'btn btn-large btn-primary', method: "get") %>
  </div><!-- /container -->
</div><!-- /slide5 --> 

app/views/layouts/_header.html.erb
<div class="header" style="font-family: 'Cabin', sans-serif">
  <div class="title">NiteLife</div>
    <canvas id="canvas" width="1400" height="200">
      <%= image_tag "canvas_image3.jpg" %>
    </canvas>
</div>
<div class="navbar">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <div class="sr-only">Toggle navigation</div>
            <div class="icon-bar"></div>
            <div class="icon-bar"></div>
            <div class="icon-bar"></div>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li class="sb-toggle-left">My Stuff</li>
          <% end %> 
        
          <li><%= link_to 'Home', events_path %></li>
          <% if user_signed_in? %>
            <li><%= button_to('Logout', destroy_user_session_path, :method => :delete, class: "logot-btn") %></li>
          <% else %>
            <li><%= link_to('Login', new_user_session_path)  %></li>
          <% end %> 
        </ul>
        <%=form_tag events_path, :method => 'get', class: "navbar-form navbar-right", role: "search" do %>
          <div class="form-group">
            <%= text_field_tag(:search, params[:search], class: 'form-control') %>
            <%= submit_tag("Search", :name => nil, class: "btn") %>
          </div>
        <% end %>
      </div>
    </div> 
  </nav> 
</div>

app/views/layouts/_sidebar.html.erb
<div id="sidebar" class="">
  <ul>
    <% if user_signed_in? %>
      <li><%= link_to 'Your Created Events', user_events_path %></li>
      <li><%= link_to 'Upcoming Events', selected_events_path %></li>
      <li><%= link_to 'Selected Artist Events', selected_artists_path %></li>
    <% else %>
      <div class='note'>How did you get this open? naughty developer!</div>
    <% end %> 
  </ul>
</div>

<%= javascript_include_tag 'slidebars.min.js' %>
<script>
  (function($) {
    $(document).ready(function() {
      $("#sidebar").addClass("sb-slidebar sb-left");
      $("#sidebar ul").addClass("sidebar");
      $.slidebars();
    });
  }) (jQuery);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NiteLife</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
      <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
      <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
      <%= stylesheet_link_tag    "application", media: "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
  </head>
  <body>
    
    <%= render 'layouts/header' %>
  
    <%= render 'layouts/sidebar' %>

    <% if notice %>
      <h4 class="notice"><%= notice %></h4>
    <% end %>

    <% if alert %>
      <h4 class="alert"><%= alert %></h4>
    <% end %>

    <%= yield %>
    <div id="message"></div>

    <%= image_tag "python_foot.png", :id => "python", :style => "display:none" %>
    <div class="footer">
      <p><a href="#" id="buttonx">NiteLife</a><%= image_tag('note.png', :alt => 'banana logo', :class => 'banana') %></p>
    </div>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <%= image_tag "raptor.png", :id => "elRaptor", :style => "display:none" %>
    <%= javascript_include_tag 'libs/canvas_scroll' %>
  </body>
</html>

app/views/layouts/landing/landing.html.erb
<!DOCTYPE <html>
<head lang="en">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  
  <title>NiteLife</title> 
  <%= stylesheet_link_tag "application", :media => "all" %>    
</head>
<body id="landing-page">

  <%= yield %>

</body>
</html>

app/views/selected_artists/index.html.erb
<div class="description">
	<h3>Upcoming Events from your favourite Artists</h3>
	<p id="desc">When you follow and artist, all there upcoming gigs will appear on this page</p>
	<div class="quote">
		<p><em>"We should consider <strong>every day</strong> lost on which we have not <strong>danced</strong> at least once"</em>, Nietzch</p>
	</div>
</div>

<div class="event_box">
  <% unless current_user.artist_events.any?  %>
    <div class="warning">
       <h4>Oh no! It seems you dont have any selected artists, go and find some!</h4>
    </div>
  <% else %>
    <% current_user.artist_events.each do |event| %>
      <% if event.date >= Date.today %>
      <div class"event-box">
      	<%= render event %>
      	</div>
      <% end %>
  	<% end %>
  <% end %>
</div>

app/views/selected_events/_selected_event.html.erb
<%= stylesheet_link_tag "selected_events", :media => "all" %> 

<div class="selected_event_box">
  <div class="selected-event-photo">
    <% if event.photo_url %>
      <img src="<%= event.photo_url %>" >
    <% else %>
      <%= image_tag event.photo.url(:strip) %>
    <% end %>
  </div>
  <div class="selected-event-name">
    <h2><%= link_to event.name, event_path(event) %></h2>
      <div id='selected-event-info'>
        <h3><%= event.artist.name %></h3>
        <p><%= event.venue %></p>
        <p><%= event.date.strftime("%m/%d/%Y") %> - <%= event.time.strftime("%I:%M%p") %></p>
      </div>
  </div>
  <div class='remove-event confirmable'>
    <%= button_to('Remove', selected_event_path(selected_event), class: 'btn btn-large btn-primary', method: :delete, data: {confirm: 'Are you sure?' })%>
    <p class='are_you_sure'><em>Are you sure?</em></p>
  </div>
</div>

app/views/selected_events/index.html.erb
<div class="description">
	<h3>Upcoming Events</h3>
	<p id="desc">On this page you can view all the events you have selected, <br>
	   we will send you an reminder on the day to ensure you don't miss out! </p>
	<div class="quote">
		<p><em>...And the night shall be <strong>filled with music</strong>,</p> 
		<p>And the cares, that infest the day,</p>
		<p>Shall fold their tents like the Nomads,</p>
		<p>and <strong>silently steal away</strong>...</em></p>
		<p>Henry Longfellow</p>
	</div>
</div>

<h2>Upcoming Events</h2>

<% unless current_user.interested_events.any?  %>
  <div class="warning">
     <h4>Oh no! It seems you dont have any selected events, go and find some!</h4>
  </div>
<% else %>
  <% current_user.selected_events.each do |selected_event| %>
    <% if selected_event.event.date >= Date.today %>
      <%= render selected_event, event: selected_event.event %>
    <% end %>
  <% end %>
<% end %>

app/views/user_events/_user_event.html.erb
<div class="event-box">
  <div class="event-photo">
    <% if event.photo_url %>
      <img src="<%= event.photo_url %>" >
    <% else %>
      <%= image_tag event.photo.url(:strip) %>
    <% end %>
  </div>
  <div class="event-name">
    <h2 id='fe_text'><%= link_to event.name, event_path(event) %></h2>
    <div id='event-info'>
      <h3><%= event.artist.name %></h3>
      <p><%= event.venue %></p>
      <p><%= event.date.strftime("%m/%d/%Y") %></p>
    </div>
    <div class='remove-event-preview confirmable'>
      <%= button_to('Remove', event_path(event), class: 'btn btn-large btn-primary', method: :delete, data: {confirm: 'Are you sure?' })%>
    </div>
  </div>  
</div>

app/views/user_events/index.html.erb
<div class="description">
	<h3>Your created events</h3>
	<p id="desc">This page lists all the events that you have registered in order to keep track.</p>
	<p>In order to edit a previously saved event, click on the title and the 'edit' option</p>
	<div class="quote">
		<p><em>"And <strong>hand in hand</strong> on the edge of the sand</p>
		<p><strong>They danced</strong> in the light of the moon"</em></p>
		<p> Edward Lear, <em>The Owl and the Pussycat</em></p>
	</div>
</div>

<h3><%= link_to 'Add an event', new_event_path %></h3>
  <% @users_events.each do |event| %>
    <% if event.date >= Date.today %>
      <%= render 'user_event', event: event %>      
    <% end %>
  <% end %>